### ISSUE TITLE
Git Parser

### ISSUE THREAD

**Issue by anlawande** [alt-code/CrashMonkey#13]
getChanges (repo, branch, commitOld, commitNew) => [files:[line_numbers]]

* [x] Checkout target branch
* [x] Execute diff command
* [x] Parse changes
  * changes to files
  * new files
  * deleted files
* [x] collate results

**Comment by rchakra3** [comment]
@anlawande if you haven't already done this, I've got the same
functionality in python on my repo.

**Comment by anlawande** [comment]
@rchakra3 Thanks but implemented it already. Actually [someone else did](https://github.com/spookd/git-diff-parser). Reusability FTW.
