### ISSUE TITLE
Parsing Code for Function surrounding line

### ISSUE THREAD

**Issue by anlawande** [alt-code/CrashMonkey#14]
getFuncForLine(file, line) => {func: {name, params, loc}}

* [x] Integrate with esprima
* [x] Get outer most function
* [x] Function definition anonymous style
* [x] Get function params
* [x] If line change is not in any function (global)
* [x] If error
* [x] Function moved
* [x] Signature changed

**Comment by anlawande** [comment]
Currently only doing this for file present in working directory (current commit). Will extend GitCenter to provide file for a particular commit

**Comment by chrisparnin** [comment]
For moving, might consider this:
character bi-gram comparison.
https://github.com/chrisparnin/Codegrams/blob/master/Codegrams/Services/DiffAnalysis/SimiliarityTool.cs
