### ISSUE TITLE
Javascript type inference

### ISSUE THREAD

**Issue by anlawande** [alt-code/CrashMonkey#16]
Some links for the advanced intelligence part of the project.

* I've noticed Brackets (IDE) gives me subtle hints about the parameters of user-defined functions. I'd like to investigate how it's doing this.
![image](https://cloud.githubusercontent.com/assets/4571767/12903209/ee41ac5c-ce93-11e5-8bb8-557cc8c7f316.png)
* [Flow](https://code.facebook.com/posts/1505962329687926/flow-a-new-static-type-checker-for-javascript/) a new static type checker for JavaScript
* [Javascript type inference](http://www.ccs.neu.edu/home/dimvar/jstypes.html)

**Comment by chrisparnin** [comment]
A silly trick would be to run flow on generated tests to see if they
violate type constraints

**Comment by anlawande** [comment]
Brackets uses [tern.js](http://ternjs.net//). Looking into if we can use it for our purposes

**Comment by anlawande** [comment]
Integrated tern engine into the application. Seems to be providing sensible type inferences
