### ISSUE TITLE
Module export variants

### ISSUE THREAD

**Issue by anlawande** [alt-code/CrashMonkey#18]
* [x] [module.]exports.abc = function() {}
* [x] module.exports = function() {}
* [x] function funcName() {} [module.]exports.abc = funcName;
* [x] var funcVar = function() {}; [module.]exports.abc = funcVar;
* [ ] function funcName() {}; funcName.prototype.abc = function() {}; module.exports = funcName;

**Comment by anlawande** [comment]
Want to try experimenting with directly importing the module and inspecting what comes out of it instead of static parsing

**Comment by chrisparnin** [comment]
I've done before using require... Works ok!
