### ISSUE TITLE
Project proposal

### ISSUE THREAD

**Issue by anlawande** [alt-code/CrashMonkey#3]
#### Project Description
This project investigates ways in which automated test generation techniques can integrated into the deployment pipeline like test coverage or code linting. The advantage of such an approach is to minimize developer involvement in creating test cases while still achieving meaningful test coverage. Several test generation techniques exist like Microsoft SAGE and Randoop but these require developer knowledge, experience and effort. Instead this project aims to automate the process of test generation and integrate generation, running and reporting of test cases with the build and deployment process.

#### Project Phases and Deliverables
1. Identify areas/libraries/code samples that can be targeted for test case generation
2. Write hooks with a VCS like git to get latest code changes
3. Generate test cases based on code changes
4. Run test cases against code
5. Report results of test case runs

**Comment by chrisparnin** [comment]
Looks good to me.
